- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
Issue Number: close [7990](https://github.com/apache/incubator-doris/issues/7990)
fix spark connector unsupport STRING type.
2. Has unit tests been added: (Yes)
> [Bug-Fix][Spark-Doris-Connector] fix spark connector unsupport STRING type.

- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java
[ERROR] /root/dev-1.0.1/extension/doris-spark-connector/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java:28: error: keysType is already defined as variable keysType
[INFO]     private String keysType;
[INFO]                    ^
[ERROR] one error found
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /root/dev-1.0.1/extension/doris-spark-connector/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java:[61,19] method getKeysType() is already defined in class org.apache.doris.spark.rest.models.Schema
[ERROR] /root/dev-1.0.1/extension/doris-spark-connector/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java:[65,17] method …
> Remove redundant variable and functions which could lead to compile fail

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No
For example, suppose we try to write data to a table a, and doris has not yet created a new table, the current version, we get the error message 
```Failed to load data on BE: http:xxx```
There is no error detail information.
With the improvements, we get an error message like this.
```
Caused by: org.apache.doris.spark.exception.StreamLoadException: stream load error: errCode = 7, detailMessage = unknown table, tableName=token _price_nick_new2
```
> feat: export doris write error to spark master, no need to check executor log

- spark-doris-connector/build.sh
Due to getopt command is original version on Mac OS, when execute build.sh, it cannot parse long term options as expected, such as "--spark=2.3.4 --scala=2.11". In order to solve this problem, we need install GNU version getopt command. This pr adds version check and tips for Mac OS users.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you …
> [Fix] add tips for Mac OS users in case meeting getopt error

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
reduce the Coordinator BE load pressure
1. The BE address remains the same until the write fails. Improve cluster load balancing.
2. The Coordinator BE receiving data and distributing data to other data nodes. It receives more network traffic than other nodes.
1. The BE nodes collection is cached and refresh periodically.
2. Randomly get a new BE address from cache when writing one batch at a time.
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No)
> [improvement]Randomly get a new BE address when writing one batch at a time

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/ListUtils.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/util/TestListUtils.java
Splits large collections to normal collection to avoid the "Requested array size exceeds VM limit" exception
1.  Avoid the "Requested array size exceeds VM limit "write exception when a batch is large.
2. When the batch data is unbalanced, the same batch takes up more storage, and some take up less storage. We can also increase the batch size to avoid exceptions and reduce the write compaction pressure.
Recursively splits large collections to normal collection and serializes the collection
The exception : …
> [improvement] splits large collections to normal collection to avoid the "Requested array size exceeds VM limit" exception

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/Settings.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
Add an option to set the partition size of the final write stage
1. We can increase the parallelism of the computation and reduce the write doris parallelism to reduce write compaction pressure.
2. After the spark RDD is filtered, the number of records for each partition is small and the number of partitions is large. The writing frequency becomes high and resources are wasted.
before :
after :
> [improvement]Add an option to set the partition size of the final write stage

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
Since CacheLoader does not implement the Serializable interface, the anonymous inner class used to construct LoadingCache cannot be serialized.
The internal class BackendCacheLoader inherits CacheLoader and implements Serializable, which solves the problem that the anonymous internal class of CacheLoading cannot be serialized.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by …
> [fix] cache loader cannot be serialized

- README.md
In `README.md`, building image apache/incubator-doris is out-dated. It should be apache/doris. 
See the proposed changes 
No
Document update, unit-test is not required.
5. Has document been added or modified: (Yes/No/No Need)
Yes, updated README.md
7. Does it need to update dependencies: (Yes/No)
No
9. Are there any changes that cannot be rolled back: (Yes/No)
No
> [Doc] Update doris build image

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
array type support.
Issue Number: close #74 
> array type support.

- .github/workflows/build-extension.yml
- spark-doris-connector/build.sh
- spark-doris-connector/pom.xml
Fix `spark.minor.version` to `spark.major.version` in build scripts and pom.
> Fix `spark.minor.version` to `spark.major.version`

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
1. use `IOUtils` of `commons-io` lib for less handling details of input/output stream processing
2. remove unused `feConn` variable
3. make sure `beConn`'s input / output stream closed right after being used
4. fix the name`authEncoding` to `authEncoded`, and extract the method `getAuthEncoded` to reduce redundant code.
5. fix typo in error message for unsupported file format 
6. Has unit tests been added: (Yes/No/No Need)
7. Has document been added or modified: (Yes/No/No Need)
8. Does it need to update dependencies: (Yes/No)
9. Are there any changes that cannot be rolled back: (Yes/No)
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining …
> [Improve] Code improvement in loadBatch method of DorisStreamLoad

- .github/workflows/build-extension.yml
- upgrade `setup-java` action to v3-
- change distribution to  `temurin` , since `AdoptOpenJDK got moved to Eclipse Temurin and won't be updated anymore.`
- enable caching for maven dependencies
> Upgrade `setup-java` action to v3 and change distribution to `temurin`

- .github/workflows/build-extension.yml
- Set `--no-transfer-progress` option in CI maven builds for less verbose message 
> Set `--no-transfer-progress` option in maven builds for less verbose message

- spark-doris-connector/pom.xml
- Apache Parent pom release note: https://github.com/apache/maven-apache-parent/releases/tag/apache-29
- Use maven plugin version from parent pom, removing redundant maven plugin versions for compiler, javadoc and source
> Bump Apache parent pom from 23 to 29

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
- use streaming api on rdd portion in scala style, reducing reducant code and possible less memory footprint
- fix local property name `maxRowCount` to `batchSize`
> [Improve] Use streaming style on grouping, transforming and flushing RDD partitions

- .github/workflows/approve-label.yml
- .github/workflows/build-extension.yml
- .github/workflows/license-eyes.yml
- Bump checkout action in CI builds from v2 to v3 (https://github.com/actions/checkout)
> [Infra] Upgrade actions/checkout to v3

- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaValueReader.scala
- to prevent explicit use of log4j, use Spark's Logging instead
- Support Spark 3.3.0
Removed log4j 1.x, and uses Spark's Logging trait, which uses log4j 2.x in Sprak 3.3.0. For older Spark versions , this change does not break the compability. Code changes are in ScalaValueReader.scala
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives …
> [Improve] Use Spark's Logging instead of explicit usage of log4j

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
Some types do not support reading, but can be written by setting column mapping, such as bitmap, hll.
When writing in sql by creating a temporary view, you need to read the schema of the corresponding table, and an exception with message 'unsupported type' will be thrown.
So add the parameter `doris.ignore-type` to specify the type you want to ignore, and the columns of the corresponding type will be ignored when getting the schema.
If this is a relatively large or complex change, kick off …
> [improvement] add new param for ignored type

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/Settings.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/RespContent.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/ResponseUtil.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/listener/DorisTransactionListener.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
Spark doris connector support two-phase commit.
Set the option `doris.sink.enable-2pc` to `true` to enable two-phase commit for stream load.
After enabled, the behavior is as follows:
Pre-submit stream load requests for each batch load, and then
1. When the job succeeds, all pre-committed transactions will be committed.
2. When the job fails, all pre-committed transactions will be aborted.
4. Has unit tests been added: (Yes/No/No Need)
5. Has document been added or modified: (Yes/No/No Need)
6. Does it need to update dependencies: (Yes/No)
7. Are there any changes that cannot be rolled back: (Yes/No)
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) …
> [feature] support two phase commit

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
Fixed the problem that there is no default parameter when `read_json_by_line` and `strip_outer_array` are not specified in json format.
> [fix] json format load default mode

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
- read largeint type as decimal(38,0)
- read date/datev2 type as java.sql.date
> convert date/datev2 to sql date and largeint into decimal(38,0)

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisRelation.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
When reading doris with not in clause，this error ocurrs：
> Doris FE's response cannot map to schema. res: {"exception":"errCode = 2, detailMessage = Syntax error in line 1:
> select `id`,`k1` from `test`.`test2` where 1=1 and 
> Encountered: EOF
> Expected: IDENTIFIER
> ","status":400}
> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "exception" (class > > > > 
> org.apache.doris.spark.rest.models.QueryPlan), not marked as ignorable (3 known properties: "partitions", "status", > 
> "opaqued_query_plan"])
> at [Source: (String)"{"exception":"errCode = 2, detailMessage = Syntax error in line 1:
> select `id`,`k1` from `test`.`test2` where 1=1 and \n                                                   ^
> Encountered: EOF
> Expected: IDENTIFIER
> …
> [fix] not in clause is not converted correctly

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
When writing doris through structured streaming, the following exception will occur:
```java
23/09/01 14:13:40 ERROR MicroBatchExecution: Query [id = c1d9450a-43ab-46fd-9826-10e0eb8ab1bc, runId = 21bd5cfe-84a1-487f-a2e7-ce27e2813691] terminated with error
org.apache.spark.sql.AnalysisException: Queries with streaming sources must be executed with writeStream.start();
StreamingDataSourceV2Relation [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13], org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaScan@56bd0218, KafkaV2[Subscribe[spark_streaming_test]], {"spark_streaming_test":{"0":13}}, {"spark_streaming_test":{"0":14}}
at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.throwError(UnsupportedOperationChecker …
```
> [fix] streaming write execution plan error

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/listener/DorisTransactionListener.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
2pc txn commit or abort retry and interval configurable. Prevent 2pc txn submission  too slow
> [improvement] 2pc txn commit or abort retry and interval configurable.

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
NPE occurs for StringType when column value is null.
> [bug] NPE occurs for StringType when column value is null.

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatchInputStream.java
byteBuffer calculate new capacity bug fix.
> [bug] byteBuffer calculate new capacity bug fix.

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/listener/DorisTransactionListener.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
After write optimization, the upstream data is read through the iterator. Since the iterator can only traverse in one direction, the current batch cannot be reread during the internal retry.
So the solution is to remove the internal retry, and the failure exception when executing the load will be thrown.
If the `spark.task.maxFailures` parameter is set (default value is 4), or other retry-related parameters, the Spark scheduler will retry the task.
Other changes:
1. abort transaction by label when current load is failed
2. do some style changes
6. Are there any changes that …
> [fix] Fix data loss due to internal retries

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSparkConnector.scala
support read map and struct type
> [feature] support read map and struct type

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatchInputStream.java
Currently, the implementation of RecordBatchInputStream.readNext requires the introduction of additional ByteBuffer and continuous resizing, which leads to significant performance overhead. Furthermore, the current ByteBuffer resizing logic can result in overflow and enter into an infinite loop.
Therefore, it is possible to optimize and reduce the introduction of additional ByteBuffers while minimizing the performance impact caused by resizing.
If this is a relatively large or complex …
> [improve] Reduce the performance loss of additional buffer expansion.

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatch.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatchInputStream.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/listener/DorisTransactionListener.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
In the current implementation, due to traversing data through iterators and sending data in a stream, batch loading does not implement batch retry. Task retry will be performed after the load request fails, and the cost of task retry is relatively high. For some scenarios such as network jitter, batch retry is a better way
The implementation of this PR is to choose whether to retry batch loading when it fails through configuration.
The behavior is as follows：
Batch retry is enabled when sink.max-retries is set greater than 0，an iterator is implemented to cache batch data, and a count value is used to control batch writing. 
When the batch fails, reset the count and set the flag bit, and re-read the current batch data from the cache array.
1. Does it affect the original behavior: (Yes/No/I …
> [improvement] batch load retry

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
The message of the exception thrown after the load fails is enriched so that the driver can see the cause of the failure.
> [improvement] optimize log and exception message

- spark-doris-connector/src/main/java/org/apache/doris/spark/util/DataUtil.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
The return type of `InternalRow.getDecimal` is `org.apache.spark.sql.types.Decimal`,  and its serialization result is `{"zero":false}`, which is not as expected.
Now convert `org.apache.spark.sql.types.Decimal` to `java.math.BigDecimal` so that the serialized result is correct.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, …
> [fix] The result of serialization of decimal type does not meet the expected problem

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisRelation.scala
Use a grave accent to quote column names to prevent query exceptions when keywords are present in the column names.
> [fix] Query problem when column name is keyword

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
For unique tables, `__DORIS_DELET_SIGN__` is a hidden column that needs to be read during data scanning, but should not be displayed
> [bugfix]fix schema error from unique table

- README.md
- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DataFormat.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatch.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatchInputStream.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/DataUtil.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/testcase/TestStreamLoadForArrowType.scala
- spark-doris-connector/src/main/scala/org/apache/spark/sql/doris/spark/ArrowSchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
> [feature](step:one)Add arrow format

- .gitignore
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
Issue Number: https://github.com/apache/doris-spark-connector/issues/167
Since doris version 2.0.0, type jsonb is renamed to json, it is necessary to support json type reading.
> [feature] support read json type

- .github/workflows/build-extension.yml
- spark-doris-connector/pom.xml
1. add spark2.4,3.2,3.3,3.4 to workflows
2. upgrade jackson version to 2.13
> [workflows] add other spark version to compile

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatchString.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/DataUtil.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/load/TestDorisStreamLoad.java
Improve import speed by compressing data at low internet speeds。The lower the bandwidth, the better the effect。
> [Improve]Improve import speed by compressing data at low internet speeds

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
Automatic redirection is turned on by default when streamload is writing.
> [improve](write) Deafult open redirect

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
> [fix] stream load's colunms can use keyword with sparksql

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/RespContent.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/load/Loader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/load/StreamLoader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/txn/TransactionHandler.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/txn/listener/DorisTransactionListener.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/txn/listener/DorisTxnStreamingQueryListener.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
In order to facilitate the expansion of more writing methods in the future, the writing part has been reconstructed. The main reconstruction contents are as follows:
1. `Loader` API
The Loader API defines three behaviors:
- `load`: write data to doris
- `commit`: commit transaction
- `abort`: abort transaction
2. `TransactionHandler`
The `TransactionHandler` component is used to process all pre-committed transactions after the task or batch ends.
When all tasks succeed, all pre-submitted tasks will be submitted; when some tasks fail, all pre-submitted tasks will be rolled back.
The execution of transaction commit and rollback depends on the specific implementation of the `commit` and `abort` methods implemented by the loader.
Other changes:
1. update `revision` to …
> [refactor](load) Refactor the loader to expand the way data is written

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/load/StreamLoader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/util/HttpUtil.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/util/URLs.scala
- spark-doris-connector/src/test/java/org/apache/doris/spark/load/StreamLoaderTest.java
- spark-doris-connector/src/test/scala/org/apache/doris/spark/load/StreamLoaderTest.java
Issue Number: #124
1. Support FE https request.
You can set the following options to enable https: 
- Set `doris.enable.https` to `true`
- Set `doris.https.key-store-path` to the file path of a valid ssl certificate
- Set `doris.https.key-store-type` to the certificate type, the default value is `JKS`
- Set `doris.https.key-store-password` to certificate file password
Note: 
- Since BE does not currently support https, stream load through https only supports redirection by FE (setting the `doris.sink.auto-redirect` option to `true`,  which is the default value)
2. Refactor RestService 
5. Does it need to update dependencies: …
> [feature] support fe https request

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
Issue Number: close 
Compatible with arrow serialization type modifications for date/datetime in the following pr:
https://github.com/apache/doris/pull/32281
> [improvement] Compatible with arrow serialization type modifications for date/datetime

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/util/IPUtils.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
1. support read ipv4 type since Apache Doris 2.1.0
2. support read ipv6 since Apache Doris 2.1.1 , This issue arises from the incompatible conversion between IPv6 data type and Arrow data type. https://github.com/apache/doris/pull/32240
3. Apache Doris supports IPv6 format, including IPv4-mapped format represented as ::ffff.255.255.255.255  and IPv4 to IPv6 conversion represented as ::0.1.0.0.
If this is a relatively large or complex change, kick off the …
> [feature]support read ipv4/ipv6 data type

- .github/workflows/build-extension.yml
- spark-doris-connector/build.sh
- spark-doris-connector/pom.xml
> [refactor](script) optimize build scala version

- spark-doris-connector/src/main/java/org/apache/doris/spark/util/ListUtils.java
When a batch of data is too large, it will cause OOM when generatingSerializedResult, but also it is not in trycatch, a batch of data cannot be divided.
> [Improvement]Put generateSerializedResult in try catch to avoid insufficient memory caused by excessive data size

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/load/StreamLoader.scala
Issue Number: close #205 
Throw exception when commit unsuccessfully.
1. Does it affect the original behavior: (Yes)
> throw exception when commit transaction failed

- spark-doris-connector/src/main/scala/org/apache/doris/spark/load/StreamLoader.scala
Issue Number: close #211 211
Use row input stream instead of StringBuilder when write to gzip outputstream.
> decrease memory usage when csv&gzip is on

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaValueReader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisRelation.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
For the `bitmap` type, doris does not currently support reading, so the previous implementation method is to ignore the `bitmap` type field by setting the `doris.ignore-type` option.
However, when you import data into Doris by executing the `insert into select` statement, the source table and the target table have the same number of columns, and you need to map the source table columns to columns of the Doris bitmap type, the number of select columns and the number of target table columns will be inconsistent, causing Spark parsing failure.
So now the solution is as follows：
- When reading, the `bitmap` and `HLL `type columns will return the string constant 'READ UNSUPPORTED'.
- When writing, `bitmap` and `HLL` type columns are converted to bitmap type by …
> [bug] fix bitmap and hll type column access issue

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
Currently, when reading arrow, since the be layer hard-codes all datetimev2 scales to 6, arrow returns TimeStampMicroVector, which results in scale parsing errors when arrow is displayed. Refer to https://github.com/apache/doris/issues/38174
https://github.com/apache/doris-flink-connector/pull/446
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the …
> [Fix] fix arrow read timestamp bug

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/SparkSettings.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/PartitionDefinition.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/AbstractDorisRDDIterator.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/AbstractValueReader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaADBCValueReader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaDorisRDD.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaValueReader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/ScalaDorisRowADBCValueReader.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/ScalaDorisRowRDD.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestUtils.scala
> [feature] read doris via arrow flight sql 

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
1. Remove unnecessary judgments
2. add ut case
> [Fix](reader) fix arrow timezone bug

- spark-doris-connector/src/main/java/org/apache/doris/spark/backend/BackendClient.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
Caused by org.apache.doris.shaded.org.apache.thrift.transport.TirensportException(Maxessegesize reached)
> [Improve] add thrift max message size options

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisFrontendClient.java
Sometimes, even though the MySQL driver jar is included in the classpath, a "No suitable driver found" exception is thrown when calling the `DriverManager.getConnection` method.
So it is still necessary to call the `Class.forName` method to load the driver before getting the connection.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you …
> [fix](connector) fix no suitable driver found issue when getting fe jdbc connection 

- spark-doris-connector/pom.xml
- spark-doris-connector/spark-doris-connector-base/pom.xml
```scala
scala> Class.forName("com.mysql.jdbc.Driver")
25/01/06 12:48:38 ERROR : Error loading factory org.apache.doris.shaded.org.apache.arrow.driver.jdbc.ArrowFlightJdbcFactory
java.lang.ClassNotFoundException: org.apache.doris.shaded.org.apache.arrow.driver.jdbc.ArrowFlightJdbcFactory
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.apache.calcite.avatica.UnregisteredDriver.instantiateFactory(UnregisteredDriver.java:115)
at …
```
> [fix](connector) remove arrow jdbc dependency

- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/RowConvertors.scala
For DATE/DATEV2 types, the data is converted to java.sql.Date type in RowBatch. 
> [fix](connector) fix read date type convert issue

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisFrontendClient.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/AbstractThriftReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/RowBatch.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/sql/ScalaDorisRowRDD.scala
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/SchemaConvertors.scala
ERROR
```scala
org.apache.doris.spark.exception.DorisException: Spark type is VARCHAR, but arrow type is INT.
```
Fix arrow deserialize issue due to data being inconsistent with column order, and this problem occurs in Doris 3.0.3 and above versions.
> [fix](connector) fix arrow deserialize issue due to data being inconsistent with column order

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/entity/DorisReaderPartition.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/AbstractThriftReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/DorisFlightSqlReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/ReaderPartitionGenerator.java
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/AbstractDorisScan.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisPartitionReader.scala
- spark-doris-connector/spark-doris-connector-spark-3.3/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.3/src/main/scala/org/apache/doris/spark/read/DorisScanV2.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/src/main/scala/org/apache/doris/spark/read/DorisScanV2.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/src/main/scala/org/apache/doris/spark/read/DorisScanV2.scala
Support partial limit push down for reducing scan rows when execute limit query. ( Spark version >= 3.2 is required)
> [feature](connector) support partial limit push down

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/rest/models/BackendV2.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/rest/models/Field.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/rest/models/QueryPlan.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/rest/models/Schema.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/rest/models/Tablet.java
In some cases, the API will return more fields, like https://github.com/apache/doris/pull/46557. In this case, strict validation may result in errors. We can set it to ignore.
> [Improvement] add resposne ignore field config

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/DorisFlightSqlReader.java
Fix read json type issue via arrow flight sql
```plaintext
org.apache.doris.spark.exception.DorisException: Unsupported type JSON of col: xxx
at org.apache.doris.spark.client.read.RowBatch.<init>(RowBatch.java:136)
at org.apache.doris.spark.client.read.DorisFlightSqlReader.hasNext(DorisFlightSqlReader.java:93)
at org.apache.doris.spark.read.DorisPartitionReader.next(DorisPartitionReader.scala:48)
at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:120)
at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:158)
at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1(DataSourceRDD.scala:63)
at …
```
> [fix](connector) fix flight sql read json type

- spark-doris-connector/spark-doris-connector-spark-3.3/src/main/scala/org/apache/doris/spark/sql/sources/DorisDataSource.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/src/main/scala/org/apache/doris/spark/sql/sources/DorisDataSource.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/src/main/scala/org/apache/doris/spark/sql/sources/DorisDataSource.scala
when execute create table using doris, and query the table, the following exception will be thrown
```java
org.apache.spark.sql.AnalysisException: doris is not a valid Spark SQL Data 
```
> [improvement](connector) support doris spark sql datasource for create table statement in spark 3.3 and above

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/entity/DorisReaderPartition.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/AbstractThriftReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/DorisFlightSqlReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/ReaderPartitionGenerator.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/RowBatch.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/rdd/AbstractDorisRDD.scala
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/RowConvertors.scala
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/client/read/RowBatchTest.java
- spark-doris-connector/spark-doris-connector-base/src/test/scala/org/apache/doris/spark/util/RowConvertorsTest.scala
- spark-doris-connector/spark-doris-connector-spark-2/pom.xml
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/AbstractDorisScan.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisPartitionReader.scala
When `spark.sql.datetime.java8API.enabled` is configured as `true`, reading the data of date type will throw the following exception
```java
java.lang.RuntimeException: java.sql.Date is not a valid external type for schema of date
```
> [fix](connector) fix read date type err

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/AbstractThriftReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/RowBatch.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/StreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/load/StreamLoader.scala
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/RowConvertors.scala
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/SchemaConvertors.scala
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/client/read/RowBatchTest.java
1. Fixed writing issues in arrow format.
2. Map Doris `Datetime` type to Catalyst `TimestampType` (previously mapped to `StringType`)
> [fix](connector) Fixed writing issues in arrow format

- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/catalog/DorisTableBase.scala
In the spark 3.x connector, the Doris data source based on Datasource V2 is implemented. When the source schema written is different from the schema of the target table, an exception similar to the following will be thrown:
```java
org.apache.spark.sql.AnalysisException: Cannot write incompatible data to table 'db.table':
- Cannot find data for output column 'c0'
- Cannot find data for output column 'c1'.
```
Therefore, the `ACCEPT_ANY_SCHEMA` capability is added to `DorisTable` to implement the writing of partial column data.
5. Are there any changes …
> [improvement](connector) support write accept any schema

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/RowBatch.java
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/client/read/RowBatchTest.java
Following PR https://github.com/apache/doris/pull/34042, Apache Doris 2.1.3 and newer versions now serialize IPv4/IPv6 types directly from parsed strings. This PR adapts our code to maintain compatibility with this change.
> [read](data-type) compatible with ip data type

- .github/workflows/run-e2ecase.yml
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/StreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/util/EscapeHandler.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/HttpUtils.scala
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/RowConvertors.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/container/AbstractContainerTestBase.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/container/instance/ContainerService.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/container/instance/DorisContainer.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/container/instance/DorisCustomerContainer.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/Doris2DorisE2ECase.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisCatalogITCase.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisReaderITCase.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisWriterFailoverITCase.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisWriterITCase.scala
- spark-doris-connector/spark-doris-connector-it/src/test/resources/container/ddl/write_all_type.sql
- spark-doris-connector/spark-doris-connector-it/src/test/resources/log4j2-test.properties
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/write/DorisDataWriter.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/write/DorisWrite.scala
add doris sink itcase, covers the following cases
1. Write mode, dataframe, sparksql
2. Write table model, dup agg mor mow
3. All column write coverage, and end-to-end test
4. Direct fe/be write
5. csv hidden delimiter, csv/json/arrow format write
6. group commit write
7. doris catalog case
8. 2pc write, insert overwrite
9. streamload failover case etc.
10. Has unit tests been added: (Yes/No/No Need)
11. Has document been added or modified: (Yes/No/No Need)
12. Does it need to update dependencies: (Yes/No)
13. Are there any changes that cannot be rolled back: (Yes/No)
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the …
> [improve] add doris sink itcase

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisWriterFailoverITCase.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/write/DorisDataWriter.scala
If the stream load http request ends before a batch of data is sent for some reason, the writer thread will be stuck. If you get the thread stack through jstack, you will see the following situation:
```java
"stream-load-worker-0" #58 daemon prio=5 os_prio=31 tid=0x00000001150c9000 nid=0xaf03 waiting on condition [0x000000030479e000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000007bba4c428> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
at …
```
> [fix](connector) Fixed the issue where the loading task got stuck when stream load ended unexpectedly 

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisFrontendClient.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisReaderITCase.scala
Issue Number: close  https://github.com/apache/doris/issues/49441
Pushing down Chinese will result in an error when use thrift mode query. This was missed during the reconstruction.  https://github.com/apache/doris-spark-connector/blob/release-1.3.2/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java#L254-L257
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and …
> [Fix] Fixed the problem that the query could not be performed when pushing utf8 encoding

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/DorisFlightSqlReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisReaderITCase.scala
1. Add configuration DORIS_READ_FLIGHT_SQL_PREFIX to specify the SQL prefix, which is convenient for operation and maintenance to query the source of table reads
2. Add fe retry and fe random strategy when initializing the adbc connection to achieve the goal of FE load balancing
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you …
> [Enhancemant] Add fe retry and load balancing strategy for Doris Flight SQL Reader

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/util/LoadBalanceListTest.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/catalog/DorisTableBase.scala
When Spark is processing, if the number of upstream and downstream fields does not match, an error will be reported during SparkSQL verification. Adding the switch `doris.write.schemaless` solves this problem.
```
org.apache.spark.sql.AnalysisException: [INCOMPATIBLE_DATA_FOR_TABLE.CANNOT_FIND_DATA] Cannot write incompatible data for the table `example_db`.`table_schema_less`: Cannot find data for the output column `username`.
at org.apache.spark.sql.errors.QueryCompilationErrors$.incompatibleDataToTableCannotFindDataError(QueryCompilationErrors.scala:2136)
at org.apache.spark.sql.catalyst.analysis.TableOutputResolver$.$anonfun$reorderColumnsByName$1(TableOutputResolver.scala:191)
at scala.collection.immutable.List.flatMap(List.scala:366)
at …
```
> [Improve] add schema less option
