apache/doris-spark-connector

- .asf.yaml
move GitBox mail to commits@doris
> [community] move GitBox mail to commits@doris

- .asf.yaml
> unprotected

- .asf.yaml
- .github/workflows/build-extension.yml
- CONTRIBUTING.md
- CONTRIBUTING_CN.md
- NOTICE.txt
- spark-doris-connector/build.sh
- spark-doris-connector/pom.xml
> [chore] modify some script for building connector

- spark-doris-connector/pom.xml
> [chore] add release plugin

- .asf.yaml
- spark-doris-connector/build.sh
- spark-doris-connector/pom.xml
1. modify GAV to "spark-doris-connector-{spark.minor.version}_${scala_version}"
> [chore] Change GAV

- README.md
A minor PR, change links in README from http to https
> Docs: Change http to https

- spark-doris-connector/build.sh
> [chore] fix name bug in build.sh

- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java
> [fix] Deserialization failed caused by the undefined field: keysType

- spark-doris-connector/src/main/java/org/apache/doris/spark/CachedDorisStreamLoadClient.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
Issue Number: close #14
Stream load data is converted to json format.
> [improvement] stream load data is converted to json format

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
Issue Number: close #25 
Optimize log, change flush retry log from warn to debug
1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: Yes
> [improvement](log) change flush retry log from warn to debug

- .gitignore
- .licenserc.yaml
- README.md
- spark-doris-connector/build.sh
- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/rest/TestRestService.java
- spark-doris-connector/src/test/resources/data.csv
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSparkConnector.scala
Issue Number: close #23
Support using Spark3.2 version to compile and test
> [feature] Support Spark3.2 compilation

- README.md
1. add a quick start for README.md
> add quick start steps

- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
> [Fix] fix unit test compile error

- spark-doris-connector/pom.xml
Fix pom.xml when compile occur error.
> [fix] Fix pom.xml when compile occur error.

- README.md
- spark-doris-connector/pom.xml
> remove incubating

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
I want to setting  max_filter_ratio  greater than 0.
> [Enhancement] Add param max_filter_ratio for sink of spark connector 

- .asf.yaml
> [TLP] remove incubator

- README.md
> [doc]Modify click link invalid problem

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
Issue Number: close #47 
stream dataframe can write to doris
No
No Need
5. Has document been added or modified: (Yes/No/No Need)
No Need
7. Does it need to update dependencies: (Yes/No)
No
9. Are there any changes that cannot be rolled back: (Yes/No)
No
> [bug] fix stream dataframe writing to doris json parse exception

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
> spark-doris-connector supports stream load parameter

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
> [bug]fix stream load parameter bug

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSparkConnector.scala
Return specific error information after optimizing the exception
> Return specific error information after optimizing the exception

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
> [improvement] Adapt to the load format of csv && set the default load format

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/main/thrift/doris/Types.thrift
support datev2/datatimev2/decimalv3 type
> [feature] support datev2/datatimev2/decimalv3 type

- spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
1. Does it affect the original behavior: NO
2. Has unit tests been added:NO
3. Has document been added or modified: NO
4. Does it need to update dependencies:NO
5. Are there any changes that cannot be rolled back: NO
> [improvement](spark-connector)Supports traversal of Doris FE nodes when searching for Doris BE

- .github/workflows/build-extension.yml
> [fix]fix thrift compiler

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
> [feature] support jsonb type

- spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
- Refactor DorisStreamLoad to use `httpclient` for handling HTTP requests and repsonses
> Introduce `httpclient` for sending requests in DorisStreamLoad

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
For the previous code, each load failure will cause an `IOException` to be thrown.
Therefore, the `loadSuccess` flag is added. When the load is successfully executed, set the flag to true. After the retry cycle ends, check the `loadSuccess` flag. When it is false, it means that the load still fails after retrying the specified times, and an `IOException` is thrown at this time.
If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by …
> [fix] add load success flag and check after retry loop

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/CachedDorisStreamLoadClient.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
> [refactor] Unified writing through DorisWriter

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
> [improvement] update default sink.batch.size to 100000

- spark-doris-connector/src/main/java/org/apache/doris/spark/backend/BackendClient.java
Not print the password in debug log
> Fix print the password in debug log

- .gitignore
Add the ide directory to `.gitignore` file
> add the ide directory to .gitignore

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/EscapeHandler.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/util/EscapeHandlerTest.java
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
> [improvement] Escaping special characters

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/ListUtils.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/util/TestListUtils.java
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
json format support json by line mode
> [improvement] json format support json by line mode

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/DataUtil.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/util/DataUtilTest.java
Issue Number: close #128 
support spark array type write
> [feature] support spark array type write

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/DataUtil.java
write date type error with json format 
> [fix] write date type error with json format 

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/SchemaUtilsTest.scala
> [improvement] map and struct type write format

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
Currently, when a value of the array type is null, rowColumnValue will encounter a null pointer
I suggest that when processing arrays, consider the case of null and return null.
> [fix](load) fix npe when array is null

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/jdbc/JdbcUtils.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisRelation.scala
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
support overwrite save mode.
When save mode is overwrite, table will be truncated before loading
> [feature] support overwrite save mode

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
Fixed the following issues:
1. writing map and struct type field npe when then field is null 
2. reading map type field npe when key or value is null
> [fix] complex type npe problem

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/DorisStreamLoad.java
> [improve] remove table path from 2pc url

- spark-doris-connector/build.sh
add spark 3.4 option and scala compatibility check
> [chore] update build script

- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
> [fix] fix retry read buffer problem

- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
> [improve] improve batch iterator has next check

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
> [fix] write timestamp type precision lost problem

- spark-doris-connector/src/main/java/org/apache/doris/spark/load/RecordBatchInputStream.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/util/DataUtil.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/util/DataUtilTest.java
> [fix] null value is written as null string in csv format

- README.md
> [Improve] Add how to build on README

- spark-doris-connector/pom.xml
> [fix] remove scala library dependency when packaging to avoid conflicts

- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
When we use reparation, since the rdd is transferred after rdd.queryExcetion, its physical plan may still be persisted, so after rdd repartition, the data may not meet expectations.
> [Bug] Fix data duplication caused by repartition

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/rest/TestRestService.java
> [improvement] change config default value for read optimization

- spark-doris-connector/pom.xml
- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
> [feature] support variant type

- spark-doris-connector/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
After loading retry is enabled, the batch needs to be cached by adding the next object of the iterator to the ArrayBuffer. Since the memory of the next object is reused, objects with the same memory address are added to the array multiple times. , so when retrying to traverse the buffer, all the objects read are the last objects obtained by the iterator.
Fix: copy the next object of the iterator and save the copy in the buffer.
If this is a relatively large or complex change, kick off the …
> [fix] Fix data duplication issue when retrying

- spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/Utils.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestUtils.scala
> [feature] support not equals and like and not like filter push down

- spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
- spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
> [bug] Fix read datetime field occur LocalDateTime convert String error. 

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/load/StreamLoader.scala
- spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestConnectorWriteDoris.scala
suppport stream load with group commit mode
> [feature]support group commit

- spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
- spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaValueReader.scala
> [improvement] change batch size default value and add max limitation

- spark-doris-connector/pom.xml
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/rest/PartitionDefinition.java
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/rest/TestRestService.java
> [typo] change version

- spark-load/spark-load-dpp/pom.xml
> [fix](spark-load) shade jackson to avoid conflict

- .github/workflows/build-extension.yml
> [fix](connector) fix build extension workflow for spark 2 scala 2.12

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/DorisFlightSqlReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisConfig.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/rdd/AbstractDorisRDD.scala
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/sql/sources/DorisRelation.scala
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/rest/TestRestService.java
- spark-doris-connector/spark-doris-connector-spark-2/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
- spark-doris-connector/spark-doris-connector-spark-3/src/main/scala/org/apache/doris/spark/catalog/DorisTable.scala
- spark-doris-connector/spark-doris-connector-spark-3/src/main/scala/org/apache/doris/spark/catalog/DorisTableCatalog.scala
- spark-doris-connector/spark-doris-connector-spark-3/src/main/scala/org/apache/doris/spark/sql/sources/DorisDataSourceV2.scala
> [fix](connector) Fix catalog config check 

- spark-doris-connector/pom.xml
> [fix](connector) remove incorrect surefire version

- spark-doris-connector/pom.xml
> [Chore] remove parent pom deploy skip

- .github/workflows/run-itcase-12.yml
- .github/workflows/run-itcase-20.yml
- spark-doris-connector/spark-doris-connector-it/pom.xml
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisReaderITCase.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/AbstractDorisScan.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisScan.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisScanBuilderBase.scala
- spark-doris-connector/spark-doris-connector-spark-3.2/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.3/pom.xml
- spark-doris-connector/spark-doris-connector-spark-3.3/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.3/src/main/scala/org/apache/doris/spark/read/DorisScanV2.scala
- spark-doris-connector/spark-doris-connector-spark-3.3/src/main/scala/org/apache/doris/spark/read/expression/V2ExpressionBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.3/src/test/scala/org/apache/doris/spark/read/expression/V2ExpressionBuilderTest.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/pom.xml
- spark-doris-connector/spark-doris-connector-spark-3.4/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/src/main/scala/org/apache/doris/spark/read/DorisScanV2.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/src/main/scala/org/apache/doris/spark/read/expression/V2ExpressionBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.4/src/test/scala/org/apache/doris/spark/read/expression/V2ExpressionBuilderTest.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/pom.xml
- spark-doris-connector/spark-doris-connector-spark-3.5/src/main/scala/org/apache/doris/spark/read/DorisScanBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/src/main/scala/org/apache/doris/spark/read/DorisScanV2.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/src/main/scala/org/apache/doris/spark/read/expression/V2ExpressionBuilder.scala
- spark-doris-connector/spark-doris-connector-spark-3.5/src/test/scala/org/apache/doris/spark/read/expression/V2ExpressionBuilderTest.scala
> [feature](connector) support datasource v2 pushdown

- spark-doris-connector/pom.xml
- spark-load/pom.xml
> [typo] update version

- NOTICE.txt
> [Chore] update notice for 2025

- spark-load/pom.xml
- spark-load/spark-load-common/src/main/java/org/apache/doris/common/DppResult.java
- spark-load/spark-load-core/src/main/java/org/apache/doris/SparkLoadRunner.java
- spark-load/spark-load-core/src/main/java/org/apache/doris/common/Constants.java
- spark-load/spark-load-core/src/main/java/org/apache/doris/common/enums/StorageType.java
- spark-load/spark-load-core/src/main/java/org/apache/doris/config/JobConfig.java
- spark-load/spark-load-core/src/main/java/org/apache/doris/load/job/PullLoader.java
- spark-load/spark-load-dpp/pom.xml
- spark-load/spark-load-dpp/src/main/java/org/apache/doris/load/loadv2/etl/SparkEtlJob.java
Supports executing jobs based on s3.
Relative doris pr: https://github.com/apache/doris/pull/47978
> [feature](spark load) support s3

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/RowBatch.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/RowConvertors.scala
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/client/read/RowBatchTest.java
- spark-doris-connector/spark-doris-connector-base/src/test/scala/org/apache/doris/spark/util/RowConvertorsTest.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisPartitionReader.scala
> [fix](connector) fix read map type convert error

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisFrontendClient.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
add log for stream load response
> [improvement](connector) add log for stream load response

- .github/workflows/build-extension.yml
- spark-load/spark-load-common/src/main/java/org/apache/doris/common/DppResult.java
- spark-load/spark-load-core/src/main/java/org/apache/doris/config/JobConfig.java
- spark-load/spark-load-core/src/test/java/org/apache/doris/config/JobConfigTest.java
- spark-load/spark-load-core/src/test/java/org/apache/doris/load/job/PullLoaderTest.java
> [fix](spark load) fix ut and add build spark load ci

- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisScanBuilderBase.scala
When reading data without specifying the columns to read, the following exception is thrown:
```java
java.lang.ArrayIndexOutOfBoundsException: 0
at org.apache.doris.spark.read.DorisPartitionReader.$anonfun$get$1(DorisPartitionReader.scala:60)
at org.apache.doris.spark.read.DorisPartitionReader.$anonfun$get$1$adapted(DorisPartitionReader.scala:56)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at org.apache.doris.spark.read.DorisPartitionReader.get(DorisPartitionReader.scala:56)
at org.apache.doris.spark.read.DorisPartitionReader.get(DorisPartitionReader.scala:31)
at …
```
> [fix](connector) fix npe caused by prune columns

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisBackendHttpClient.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisFrontendClient.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/test/java/org/apache/doris/spark/client/entity/StreamLoadResponseTest.java
> [improvement](connector) improve log message

- tools/releasing/create_release_branch.sh
- tools/releasing/create_source_release.sh
- tools/releasing/deploy_staging_jars.sh
- tools/releasing/update_branch_version.sh
> [Improve](release) add release script 

- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/util/DorisDialects.scala
> [fix](connector) fix filter in clause compilation

- spark-load/spark-load-core/src/main/java/org/apache/doris/SparkLoadRunner.java
- spark-load/spark-load-core/src/test/java/org/apache/doris/SparkLoadRunnerTest.java
- spark-load/spark-load-core/src/test/resources/core-site.xml
- spark-load/spark-load-core/src/test/resources/hdfs-site.xml
- spark-load/spark-load-core/src/test/resources/yarn-site.xml
> [improve](spark load) support load hadoop conf from resource

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
> [fix](connector) fix npe when empty partition commit txn

- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/read/DorisScanBuilderBase.scala
> [fix](connector) fix prune column result isn't pushed down issue

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/RowBatch.java
> [fix](connector) support read DECIMAL128 type

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisBackendThriftClient.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/read/AbstractThriftReader.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
> [improve](connector) add be thrift read log

- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisStreamingWriterITCase.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisWriterFailoverITCase.scala
> [Improve](test) add structured streaming case

- README.md
A minor typo was found in the README file. The typo was corrected to improve documentation quality.
3. Has document been added or modified: (Yes)
> [Docs](Readme) Fix typo in the README

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-base/src/main/scala/org/apache/doris/spark/sql/Utils.scala
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisWriterFailoverITCase.scala
- spark-doris-connector/spark-doris-connector-spark-2/src/main/scala/org/apache/doris/spark/writer/DorisWriter.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/write/DorisDataWriter.scala
add retry interval when load fail.
> [improvement] add retry interval when load fail

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/DorisFrontendClient.java
Add code checks in the fe init method to make error messages more readable.
> add code check for fe request

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/entity/StreamLoadResponse.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
> [improve] improve stream load log 

- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/client/write/AbstractStreamLoadProcessor.java
- spark-doris-connector/spark-doris-connector-base/src/main/java/org/apache/doris/spark/config/DorisOptions.java
- spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala
- spark-doris-connector/spark-doris-connector-spark-3-base/src/main/scala/org/apache/doris/spark/catalog/DorisTableBase.scala
[[# Proposed changes
Issue Number: close #323 
]
(https://github.com/apache/doris-spark-connector/issues/323)](https://github.com/apache/doris-spark-connector/issues/323)
> change accept_any_schema to options
